### ISSUE TITLE
rumtricks update-self creating duplicates

### ISSUE THREAD

**Issue by mobedoor** [goldenboy313/rumtricks#2]
Hello.
Running rumtricks update-self from my path throws the following
`File already exists. Renamed to /home/linuxuser/.local/bin/rumtricks.1.sh.`

Expectation
Downloaded file replaces script.

**Comment by Baltrust** [comment]
Hi.
seems to only be an issue if using aria2c since it doesn't overwrite files by default.
fixed in commit https://github.com/goldenboy313/rumtricks/commit/47668de7ffdf0afb47f1dad5dd3c1f5e94631fc4.
Closing the issue.
